export const about = {
  bio: [
    "Hello — I'm a product manager with roots in QA. I'm currently leading a delivery app used by couriers and drivers.",
    "I work in a cross-domain environment, managing touchpoints across business units. I collaborate closely with backend, mobile, and QA engineers; together we build and improve products that keep our delivery operation running.",
    "If I were to talk about my personal characteristics, I enjoy the work I do and solving the challenges that arise while doing it, and moving forward.",
    "I can say that I get a little bored during periods without challenges.",
    "With these challenges, I make mistakes, and after seeing the consequences of these mistakes, I directly see how to proceed in the next phase, with both positive and negative effects.",
    "These challenges occur not only in professional life but also in people's personal lives, and what's important is to learn from experiences and move forward in the marathon we call life, no matter what.",
    "What happened, happened; we need to move on.",
    'As Rocky said, "How hard you can get hit and keep moving forward."',
    "I'm learning Generative AI, catching up with new trends, and thinking about what I'll need in that future. I decided to build this portfolio partly to explore no-code AI tools. So here we are!",
  ],
  philosophy: [
    "I was always more interested in understanding and improving products and systems than in using them — that's what pushed me to become a product manager.",
    "The intersection of people, technology, and decision-making processes is both enjoyable and challenging for me. I feel satisfied when I see the impact or outcome of the decisions I've made.",
    "As a child, I played basketball and dreamed of playing in the NBA, but I knew it would be very difficult or that it would remain just a dream.",
    "However, I enjoyed dreaming about it and always strived to succeed, doing extra training, getting injured, then training again, but I never considered giving up.",
    "Our profession constantly presents challenges: time constraints, limited resources, unmet demands, and much more. I enjoy trying to overcome these challenges and thinking about them.",
    "But of course, I would have preferred to play in the NBA rather than preparing for this stage. 😊",
    "To summarize, I chose this profession to be able to interact with the systems and products that people use, and I am happy with it.",
  ],
  interests: [
    "Product Development",
    "UI & UX",
    "0 to 1",
    "Data Driven Product",
    "AI Tools",
    "Generative AI",
    "Cross-functional collaboration",
    "Building Mobile Products",
    "Crafting Panel Experiences",
    "Dancing with chaos",
  ],
} as const;
